#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Compute the Routing Stiffness Score (RSS).

This script follows the paper definition of RSS:

1. For each token and layer, collect router logits for the selected experts.
2. Identify z_(k), the weakest selected expert logit.
3. Identify z_(k+1), the strongest excluded expert logit.
4. Compute the margin z_(k) - z_(k+1).
5. Optionally estimate routing-set stability under bounded perturbations.

The script expects `results_all.jsonl` records generated by the updated
postprocessing pipeline, which stores:
  - expert_ids: selected expert ids
  - logits: logits aligned with selected experts
  - next_expert_logit: the strongest unselected expert logit
"""

import argparse
import json
import os
from collections import defaultdict
from typing import Any, Dict, List, Optional

import numpy as np
from tqdm import tqdm


def load_aligned_data(input_file: str) -> List[Dict[str, Any]]:
    print(f"Loading data: {input_file}")
    records: List[Dict[str, Any]] = []

    with open(input_file, "r", encoding="utf-8") as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip():
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                print(f"Warning: failed to parse line {line_num}: {exc}")

    print(f"Loaded {len(records)} records")
    return records


def prepare_records(
    records: List[Dict[str, Any]],
    num_samples: Optional[int] = None,
    random_seed: Optional[int] = None,
) -> List[Dict[str, Any]]:
    if num_samples is None or num_samples >= len(records):
        return records

    rng = np.random.default_rng(random_seed)
    indices = rng.choice(len(records), size=num_samples, replace=False)
    return [records[int(i)] for i in indices]


def infer_topk(layer_data: Dict[str, Any]) -> int:
    expert_ids = layer_data.get("expert_ids", [])
    return len(expert_ids)


def extract_layer_margin(
    layer_data: Dict[str, Any],
) -> Optional[Dict[str, Any]]:
    expert_ids = layer_data.get("expert_ids", [])
    logits = layer_data.get("logits", [])
    next_expert_logit = layer_data.get("next_expert_logit")

    if not expert_ids or not logits:
        return None

    if len(logits) != len(expert_ids):
        return None

    if next_expert_logit is None:
        return None

    weakest_selected_logit = float(min(logits))
    strongest_unselected_logit = float(next_expert_logit)
    margin = weakest_selected_logit - strongest_unselected_logit

    return {
        "margin": float(margin),
        "weakest_selected_logit": weakest_selected_logit,
        "strongest_unselected_logit": strongest_unselected_logit,
        "topk": infer_topk(layer_data),
    }


def perturbation_keeps_topk(
    selected_logits: np.ndarray,
    next_logit: float,
    perturbation_scale: float,
    rng: np.random.Generator,
) -> bool:
    """
    Estimate whether the selected set remains unchanged under bounded logit perturbation.

    We use an adversarially relevant but still simple test:
    - perturb each selected logit independently in [-eps, eps]
    - perturb the strongest excluded logit independently in [-eps, eps]
    - the top-k set remains unchanged iff the perturbed weakest selected logit
      still exceeds the perturbed strongest excluded logit
    """
    selected_noise = rng.uniform(-perturbation_scale, perturbation_scale, size=selected_logits.shape)
    next_noise = rng.uniform(-perturbation_scale, perturbation_scale)

    perturbed_selected = selected_logits + selected_noise
    perturbed_next = next_logit + next_noise

    return float(np.min(perturbed_selected)) > float(perturbed_next)


def calculate_rss_by_layer(
    records: List[Dict[str, Any]],
    num_simulations: int = 1000,
    perturbation_scale: float = 0.0,
    random_seed: Optional[int] = None,
) -> Dict[str, Any]:
    rng = np.random.default_rng(random_seed)
    layer_entries: Dict[str, List[Dict[str, Any]]] = defaultdict(list)

    for record in tqdm(records, desc="Collecting layer margins"):
        layers = record.get("layers", {})
        for layer_id, layer_data in layers.items():
            margin_entry = extract_layer_margin(layer_data)
            if margin_entry is not None:
                layer_entries[layer_id].append(
                    {
                        **margin_entry,
                        "selected_logits": [float(x) for x in layer_data.get("logits", [])],
                    }
                )

    layer_results: Dict[str, Any] = {}
    all_margins: List[float] = []
    all_stability_rates: List[float] = []

    for layer_id in sorted(layer_entries.keys(), key=int):
        entries = layer_entries[layer_id]
        margins = [entry["margin"] for entry in entries]
        weakest_logits = [entry["weakest_selected_logit"] for entry in entries]
        next_logits = [entry["strongest_unselected_logit"] for entry in entries]

        stability_rate: Optional[float] = None
        if perturbation_scale > 0 and num_simulations > 0:
            stable_count = 0
            total_trials = 0
            for entry in entries:
                selected_logits = np.array(entry["selected_logits"], dtype=float)
                next_logit = float(entry["strongest_unselected_logit"])
                for _ in range(num_simulations):
                    total_trials += 1
                    if perturbation_keeps_topk(
                        selected_logits,
                        next_logit,
                        perturbation_scale,
                        rng,
                    ):
                        stable_count += 1
            stability_rate = stable_count / total_trials if total_trials > 0 else None

        layer_results[layer_id] = {
            "rss_margin": float(np.mean(margins)),
            "margin_std": float(np.std(margins)),
            "weakest_selected_logit_mean": float(np.mean(weakest_logits)),
            "strongest_unselected_logit_mean": float(np.mean(next_logits)),
            "num_samples": len(entries),
            "topk": int(entries[0]["topk"]) if entries else 0,
            "perturbation_scale": perturbation_scale,
            "stability_rate": stability_rate,
        }

        all_margins.extend(margins)
        if stability_rate is not None:
            all_stability_rates.append(stability_rate)

    return {
        "metric_name": "routing_stiffness_score",
        "definition": "mean_logit_margin_with_optional_perturbation_stability",
        "num_records": len(records),
        "num_simulations": num_simulations,
        "perturbation_scale": perturbation_scale,
        "layer_results": layer_results,
        "global_rss_margin": float(np.mean(all_margins)) if all_margins else 0.0,
        "global_margin_std": float(np.std(all_margins)) if all_margins else 0.0,
        "global_stability_rate": (
            float(np.mean(all_stability_rates)) if all_stability_rates else None
        ),
    }


def save_results(results: Dict[str, Any], output_file: str) -> None:
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    print(f"Saved RSS results to: {output_file}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compute Routing Stiffness Score (RSS)")
    parser.add_argument("--input_file", required=True, help="Path to results_all.jsonl")
    parser.add_argument("--output_file", required=True, help="Output JSON path")
    parser.add_argument(
        "--num_samples",
        type=int,
        default=None,
        help="Number of records to sample. Defaults to all.",
    )
    parser.add_argument(
        "--num_simulations",
        type=int,
        default=1000,
        help="Number of perturbation Monte Carlo simulations per token when perturbation_scale > 0.",
    )
    parser.add_argument(
        "--perturbation_scale",
        type=float,
        default=0.0,
        help="Bounded perturbation scale applied to logits for top-k stability estimation.",
    )
    parser.add_argument("--random_seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    records = load_aligned_data(args.input_file)
    sampled_records = prepare_records(records, args.num_samples, args.random_seed)
    results = calculate_rss_by_layer(
        sampled_records,
        num_simulations=args.num_simulations,
        perturbation_scale=args.perturbation_scale,
        random_seed=args.random_seed,
    )
    save_results(results, args.output_file)


if __name__ == "__main__":
    main()
